### ISSUE TITLE
Assets Loading Over HTTP

### ISSUE THREAD

**Issue by cenders** [hust220/medusadock-web#1]
There is an image being loaded over HTTP [here](https://github.com/hust220/medusadock-web/blob/master/src/App.vue#L163) that causes the page to throw mixed content warnings in certain browsers. Ideally, this asset should be loaded over HTTPS somehow.

This can be fixed by:

- Linking to a version of the file via HTTPS
- Hosting the file and serving it over HTTPS
- Removing the file completely

**Comment by hust220** [comment]
Thank you Collin! I just put the picture in the local assets folder to solve the issue: [here](https://github.com/hust220/medusadock-web/blob/master/src/App.vue#L163)

**Comment by cenders** [comment]
This issue was resolved in https://github.com/hust220/medusadock-web/commit/f9ec369ac6e733b49190bcf9e186ce47b630ebaa. Build passes and works correctly.
